-- Baseline de esquema (Fase4): antes vivia repartido entre schema.sql (facturas/lineas/costo
-- operativo) y ddl-auto=update (app_user y delivery_log, generadas por Hibernate a partir de
-- las entidades). Flyway pasa a ser la unica fuente de verdad; ddl-auto queda en "validate".

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(80) NOT NULL,
    password_hash varchar(255) NOT NULL,
    full_name varchar(150) NOT NULL,
    role varchar(20) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

CREATE TABLE delivery_invoice (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number varchar(60) NOT NULL UNIQUE,
    partner_name varchar(255) NOT NULL,
    delivery_address varchar(255),
    expected_latitude double precision,
    expected_longitude double precision,
    invoice_date date NOT NULL DEFAULT CURRENT_DATE,
    state varchar(20) NOT NULL DEFAULT 'draft',
    requires_pin boolean NOT NULL DEFAULT true,
    pin varchar(6),
    confirmed boolean NOT NULL DEFAULT false,
    confirmed_at timestamp,
    latitude double precision,
    longitude double precision,
    driver_name varchar(255),
    failed_pin_attempts int NOT NULL DEFAULT 0,
    pin_locked_until timestamp
);

CREATE TABLE delivery_invoice_line (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES delivery_invoice(id),
    description text NOT NULL,
    quantity double precision NOT NULL CHECK (quantity > 0)
);
CREATE INDEX delivery_invoice_line_parent ON delivery_invoice_line(invoice_id);

-- Horas de soporte tecnico por mes, para el showback de costo por entrega (Fase1 §4.5).
-- Es un dato operativo que varia cada mes, por eso se guarda editable en vez de una env var.
CREATE TABLE operational_cost_input (
    month date PRIMARY KEY,
    support_hours double precision NOT NULL DEFAULT 0
);

CREATE TABLE delivery_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES delivery_invoice(id),
    invoice_number varchar(60) NOT NULL,
    partner_name varchar(255),
    delivery_address varchar(255),
    driver_id bigint NOT NULL REFERENCES app_user(id),
    outcome varchar(20) NOT NULL,
    latitude double precision,
    longitude double precision,
    detail varchar(255),
    photo bytea,
    photo_content_type varchar(100),
    distance_from_expected_meters double precision,
    created_at timestamp NOT NULL
);

-- Soportan los mismos patrones de consulta que ya optimizamos en la Fase3 (listado por
-- conductor, rango de fechas para el tablero/metricas): antes no existian, aunque las
-- consultas ya filtraban/ordenaban por estas columnas.
CREATE INDEX delivery_log_driver_id ON delivery_log(driver_id);
CREATE INDEX delivery_log_invoice_id ON delivery_log(invoice_id);
CREATE INDEX delivery_log_created_at ON delivery_log(created_at DESC);
