CREATE TABLE IF NOT EXISTS delivery_invoice (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number varchar(60) NOT NULL UNIQUE,
    partner_name varchar(255) NOT NULL,
    delivery_address varchar(255),
    expected_latitude double precision,
    expected_longitude double precision,
    invoice_date date NOT NULL DEFAULT CURRENT_DATE,
    state varchar(20) NOT NULL DEFAULT 'draft',
    requires_pin boolean NOT NULL DEFAULT true,
    pin varchar(6),
    confirmed boolean NOT NULL DEFAULT false,
    confirmed_at timestamp,
    latitude double precision,
    longitude double precision,
    driver_name varchar(255)
);
CREATE TABLE IF NOT EXISTS delivery_invoice_line (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES delivery_invoice(id),
    description text NOT NULL,
    quantity double precision NOT NULL CHECK (quantity > 0)
);
CREATE INDEX IF NOT EXISTS delivery_invoice_line_parent ON delivery_invoice_line(invoice_id);
